# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodproduct',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='foodwebsite',
            options={'verbose_name': 'Web-сайт', 'verbose_name_plural': 'Web-сайты'},
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='image',
            field=models.ImageField(default=None, upload_to='files/food_sites/images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
