# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_sites', '0002_auto_20180331_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproduct',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
