# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_sites', '0003_foodproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='food_website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_website', to='food_sites.FoodWebsite', verbose_name='Сайт'),
        ),
    ]
