# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_sites', '0004_auto_20180331_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
