# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 09:48
from __future__ import unicode_literals

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import users.fields
import users.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('uid', models.CharField(max_length=255)),
                ('extra_data', users.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=False)),
                ('token', models.TextField(default='', max_length=1000)),
                ('token_secret', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'permissions': (('view_user', 'Can view'),), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.manager.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email_new',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email new'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notification',
            field=models.BooleanField(default=True, verbose_name='Receive email notification'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Select this instead of deleting accounts.', verbose_name='User is blocked'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_social_user',
            field=models.BooleanField(default=False, verbose_name='Is user registered from social network'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Profile image', upload_to='files/profile', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notification',
            field=models.BooleanField(default=True, verbose_name='Receive push notification'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='Activate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=30, unique=True, validators=[core.validators.validate_name], verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='usersocial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_social', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usersocial',
            unique_together=set([('provider', 'uid')]),
        ),
    ]
