# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180331_0548'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersocial',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='usersocial',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_new',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_notification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_social_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='push_notification',
        ),
        migrations.DeleteModel(
            name='UserSocial',
        ),
    ]
